version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 241326262250.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t hello-world .
      - docker tag hello-world 241326262250.dkr.ecr.us-east-1.amazonaws.com/containerized-app     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 241326262250.dkr.ecr.us-east-1.amazonaws.com/containerized-app
